<?php

/**
 * @file
 * Replaces numeric and date field widgets with HTML5 compatible.
 */

/**
 * Invokes hook_field_widget_form_alter().
 */
function widget_html5_field_widget_form_alter(&$element, &$form_state, $context) {
  $numeric_fields = array('number_decimal', 'number_float');
  if (in_array($context['field']['type'], $numeric_fields)
    && $element['value']['#type'] == 'textfield') {
    $element['value']['#type'] = 'html5_number';
  }
}

function widget_html5_theme($existing, $type, $theme, $path) {
  return array(
    'widget_html5_number' => array(
      'render element' => 'element',
    ),
  );
}

function widget_html5_element_info() {
  $types['html5_number'] = array(
    '#input' => TRUE,
    '#theme' => array('widget_html5_number'),
    '#autocomplete_path' => FALSE,
    '#theme_wrappers' => array('form_element'),
  );
  return $types;
}

/**
 * Builds a standard input with attributes.
 */
function _widget_html5_textfield_standard($element, $variables) {
    element_set_attributes($element, array('id', 'name', 'value', 'size', 'maxlength'));
  _form_set_class($element, array('form-text'));

  $extra = '';
  if ($element['#autocomplete_path'] && drupal_valid_path($element['#autocomplete_path'])) {
    drupal_add_library('system', 'drupal.autocomplete');
    $element['#attributes']['class'][] = 'form-autocomplete';

    $attributes = array();
    $attributes['type'] = 'hidden';
    $attributes['id'] = $element['#attributes']['id'] . '-autocomplete';
    $attributes['value'] = url($element['#autocomplete_path'], array('absolute' => TRUE));
    $attributes['disabled'] = 'disabled';
    $attributes['class'][] = 'autocomplete';
    $extra = '<input' . drupal_attributes($attributes) . ' />';
  }

  $output = '<input' . drupal_attributes($element['#attributes']) . ' />';

  return $output . $extra;
}

/**
 * Returns HTML for a textfield form element.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #value, #description, #size, #maxlength,
 *     #required, #attributes, #autocomplete_path.
 *
 * @ingroup themeable
 */
function theme_widget_html5_number($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'number';
  return _widget_html5_textfield_standard($element, $variables);
}
